[project]
name = "mcp-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.41.0",
    "mcp[cli]>=1.15.0",
    "pyautogui>=0.9.54",
]
